<a href="https://colab.research.google.com/github/SparshKapoor-CODER/PyTorch/blob/main/PyTorchOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch

In [6]:
myTorch = torch.arange(21)
myTorch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [10]:
# reshape and view

myTorch = myTorch.reshape(7,3)
myTorch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

In [15]:
myTorch = torch.arange(21)
myTorch = myTorch.reshape(7,-1)  # Call reshape as a method of the myTorch tensor.
myTorch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

# **RESHAPE vs VIEW**

In [16]:
My_new_tensor = torch.arange(10)
My_new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
My_new_tensor1 = My_new_tensor.reshape(5,2)
My_new_tensor1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
My_new_tensor2 = My_new_tensor.view(5,2)
My_new_tensor2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

To see the differences :
*https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch*

In [26]:
My_new_tensor3 = torch.arange(10)
My_new_tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
My_new_tensor4= My_new_tensor3.reshape(5,2)
My_new_tensor4

tensor([[ 0, 15],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [28]:
My_new_tensor3[1]= 15

In [30]:
My_new_tensor5 = torch.arange(10)

In [31]:
My_new_tensor5[7]

tensor(7)

In [32]:
My_new_tensor6 = My_new_tensor5.reshape(5,2)
My_new_tensor6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
My_new_tensor6 [:,0]

tensor([0, 2, 4, 6, 8])