<a href="https://colab.research.google.com/github/SparshKapoor-CODER/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

In [3]:
import torch
import numpy as np
import random

# **LISTS**

In [ ]:
myList = [[1,2,3],[3,4,5],[6,7,8]]

# **NUMPY** **ARRAYS**

In [24]:
np1= np.random.rand(3,4)
np1

array([[0.64095472, 0.4439494 , 0.24051676, 0.39887399],
       [0.36888234, 0.90823422, 0.59052949, 0.63703767],
       [0.12601331, 0.16389655, 0.9666892 , 0.6173199 ]])

# **TENSORS**

In [30]:
tensor_2d = torch.randn(3,8)
tensor_2d

tensor([[-1.3297, -1.3316,  0.0603, -0.4288,  0.7110, -1.7067,  0.2316, -0.6149],
        [ 0.0756, -0.0372, -0.1837, -0.6550,  0.4882, -1.2178,  1.3119,  1.3541],
        [ 0.6781,  2.3454,  1.5591, -0.7193, -0.4015,  0.4487, -1.3510, -0.1317]])

In [6]:
tensor_3d = torch.ones(2,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

so like this we can make tensors of any dimention of our need



Documentation


https://pytorch.org/docs/stable/tensors.html