<a href="https://colab.research.google.com/github/SparshKapoor-CODER/PyTorch/blob/main/TensorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Math Operations with PyTorch


*  Add, Substrac,product bla bla


In [1]:
import torch
import numpy as np

In [2]:
tensor_A = torch.tensor([1,2,3])
tensor_B = torch.tensor([4,5,6])

#  Addition

In [7]:
tensor_A + tensor_B

# 1+4  2+5  3+6

tensor([5, 7, 9])

In [8]:
torch.add(tensor_A,tensor_B)

tensor([5, 7, 9])

#  Substraction

In [6]:
tensor_B - tensor_A

tensor([3, 3, 3])

In [9]:
torch.sub(tensor_B,tensor_A)

tensor([3, 3, 3])

# Product

In [10]:
tensor_A * tensor_B

tensor([ 4, 10, 18])

In [11]:
torch.mul(tensor_A,tensor_B)

tensor([ 4, 10, 18])

# Devision

In [12]:
tensor_B/tensor_A

tensor([4.0000, 2.5000, 2.0000])

In [13]:
torch.div(tensor_B,tensor_A)

tensor([4.0000, 2.5000, 2.0000])

# Modulus

In [14]:
tensor_B % tensor_A

tensor([0, 1, 0])

In [16]:
torch.remainder(tensor_B,tensor_A)

tensor([0, 1, 0])

#Exponencial

In [17]:
tensor_A ** tensor_B

tensor([  1,  32, 729])

In [18]:
tensor_A.pow(tensor_B)

tensor([  1,  32, 729])